// 重要日子／Plan B guide content, shared with the app.
// src/data/app-guides.json is GENERATED by app/tool/guides/gen_guides.py — edit
// the generator there and re-run it; never hand-edit the JSON.
import guides from '../data/app-guides.json';

export const keyDates = guides.keyDates;
export const planB = guides.planB;
export const researched = guides.researched;

export const TAG_LABELS = { jupas: 'JUPAS', dse: '文憑試', eapp: 'E-APP', overseas: '海外' };

const parse = (s) => {
  const [y, m, d] = s.split('-').map(Number);
  return { y, m, d };
};

/** `2026年10月7日` */
export function zhDate(s) {
  const { y, m, d } = parse(s);
  return `${y}年${m}月${d}日`;
}

/** `2026年10月7日–12月2日`; the year is repeated only when it changes. */
export function zhRange(start, end) {
  if (!end) return zhDate(start);
  const a = parse(start);
  const b = parse(end);
  return a.y === b.y ? `${zhDate(start)}–${b.m}月${b.d}日` : `${zhDate(start)}–${zhDate(end)}`;
}

/** Dates grouped by phase, in the generator's (chronological) order. */
export function datesByPhase() {
  return keyDates.phases.map((p) => ({ ...p, dates: keyDates.dates.filter((d) => d.phase === p.key) }));
}

/** Myth/fact pairs as FAQ entries (question text mirrors what the page shows). */
export function faqFromMyths(myths) {
  return myths.map(({ myth, fact }) => ({
    q: `${myth.zh.replace(/。$/, '')}？`,
    a: fact.zh,
  }));
}

export const routeByKey = Object.fromEntries(planB.routes.map((r) => [r.key, r]));
