import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
    CheckCircle2, Globe, ChevronDown, Menu, X,
    ChevronRight, Brain, Calculator, Mic, Award
} from "lucide-react";
import { cn } from "../lib/utils";
import JupasChineseQuickCalculator from "./JupasChineseQuickCalculator";
import LANDING_STRINGS from './landingStrings.json';

// Hard-coded zh-HK copy below goes through tr(); en / zh-CN come from
// landingStrings.json (zh-CN is generated by opencc t2s). Missing key → zh-HK.
const tr = (lang, s) => LANDING_STRINGS[lang]?.[s] ?? s;
import JupasEnglishQuickCalculator from "./JupasEnglishQuickCalculator";

export const LANGUAGES = [
    { code: "zh-HK", name: "繁體中文 (香港)" },
    { code: "zh-CN", name: "简体中文" },
    { code: "en", name: "English" },
];

export const translations = {
    "zh-HK": {
        nav: { features: "功能", scores: "院校收分", faq: "常見問題", blog: "升學攻略", cta: "下載 App" },
        resultsBanner: { label: "2027 升學規劃", text: "提早比較計分方法、課程選擇同入學機會", cta: "睇升學攻略" },
        hero: {
            tagline: "JUPAS 計分器 · 入學分析 · 面試模擬",
            title: "JUPAS 計分器：一秒計好 DSE 分數",
            titleHighlight: "再睇清入學機會同出路",
            subtitle: "輸入 DSE 成績，按 417 個課程各自嘅院校公式計分，再同歷年 Median、LQ 比較。",
            bullets: [
                "八大及自資院校 417 個課程公式",
                "歷年收生位置、熱門程度同出路評級",
                "AI 大學面試模擬，1,232 條練習題",
            ],
            cta: "免費下載",
            imageAlt: "DSE Jupas 神器 App 畫面",
        },
        features: {
            title: "一個 App，由計分到面試",
            items: [
                { icon: Calculator, title: "按課程公式計分", desc: "Best 5、科目加權、加分制逐個課程處理，唔使自己翻 prospectus。" },
                { icon: Brain, title: "睇清歷年收生位置", desc: "你嘅分對比每個課程歷年 Median 同 LQ，清楚標示年份同公式限制。" },
                { icon: Award, title: "唔止睇收分", desc: "就業、薪酬、抗 AI 等 6 項出路評級，兩三個課程並排比較。" },
                { icon: Mic, title: "AI 面試官陪你練", desc: "14 個學系大類、1,232 條題目，中英雙語即時回饋。" },
            ],
        },
        faq: {
            title: "常見問題",
            items: [
                { q: "計分準唔準？數據邊度嚟？", a: "計分器依據八大及自資院校公開嘅收生計分公式（Best 5、4C+2X、科目加權、加分制等）逐一實現，並對照公開及整理所得嘅 JUPAS 課程計分資料。結果只供參考，正式收生以各院校公佈為準。" },
                { q: "覆蓋幾多個課程？", a: "目前整理 417 個唯一 JUPAS 課程資料及出路評級，包括八大院校及主要自資院校課程，並會按官方資料更新。" },
                { q: "AI 入學分析點計？", a: "AI 會將你按課程公式計出嘅分數，對比該課程歷年 median 同 LQ，解釋你與過往取錄分布嘅距離，再結合入學要求、Band、面試及出路資料作參考；結果唔係錄取概率或保證。" },
                { q: "出路評級係咩？", a: "出路評級係職涯 ROI 導向參考，417 個課程按就業前景、升學潛力、抗 AI 能力、院校排名、薪酬回報、技能複利 6 個維度評估，再用 A+ 至 C+ 顯示。它唔等同官方意見，亦唔代表課程學術價值或個人適合度。" },
            ],
        },
        cta: { title: "由放榜計到入大學", subtitle: "免費下載，即刻計你嘅 JUPAS 分數。" },
    },
    "zh-CN": {
        nav: { features: "功能", scores: "院校收分", faq: "常见问题", blog: "升学攻略", cta: "下载 App" },
        resultsBanner: { label: "2027 升学规划", text: "提早比较计分方法、课程选择和入学机会", cta: "看升学攻略" },
        hero: {
            tagline: "JUPAS 计分器 · 入学分析 · 面试模拟",
            title: "JUPAS 计分器：一秒算好 DSE 分数",
            titleHighlight: "再看清入学机会和出路",
            subtitle: "输入 DSE 成绩，按 417 个课程各自的院校公式计分，再与历年 Median、LQ 比较。",
            bullets: [
                "八大及自资院校 417 个课程公式",
                "历年收生位置、热门程度和出路评级",
                "AI 大学面试模拟，1,232 条练习题",
            ],
            cta: "免费下载",
            imageAlt: "DSE Jupas 神器 App 画面",
        },
        features: {
            title: "一个 App，从计分到面试",
            items: [
                { icon: Calculator, title: "按课程公式计分", desc: "Best 5、科目加权、加分制逐个课程处理，不必自己翻 prospectus。" },
                { icon: Brain, title: "看清历年收生位置", desc: "你的分数对比每个课程历年 Median 与 LQ，清楚标示年份和公式限制。" },
                { icon: Award, title: "不只看收分", desc: "就业、薪酬、抗 AI 等 6 项出路评级，两三个课程并排比较。" },
                { icon: Mic, title: "AI 面试官陪你练", desc: "14 个学系大类、1,232 条题目，中英双语即时反馈。" },
            ],
        },
        faq: {
            title: "常见问题",
            items: [
                { q: "计分准不准？数据从哪里来？", a: "计分器依据八大及自资院校公开的收生计分公式（Best 5、4C+2X、科目加权、加分制等）逐一实现，并对照公开及整理所得的 JUPAS 课程计分资料。结果仅供参考，正式收生以各院校公布为准。" },
                { q: "覆盖多少个课程？", a: "目前整理 417 个唯一 JUPAS 课程资料及出路评级，包括八大院校及主要自资院校课程，并会按官方资料更新。" },
                { q: "AI 入学分析怎么算？", a: "AI 会把你按课程公式算出的分数与该课程历年 median 和 LQ 比较，解释你和过往取录分布的距离，再结合入学要求、Band、面试及出路资料作参考；结果不是录取概率或保证。" },
                { q: "出路评级是什么？", a: "出路评级是职业 ROI 导向参考，417 个课程按就业前景、升学潜力、抗 AI 能力、院校排名、薪酬回报、技能复利 6 个维度评估，再用 A+ 至 C+ 显示。它不是官方意见，也不代表课程学术价值或个人适合度。" },
            ],
        },
        cta: { title: "从放榜算到进大学", subtitle: "免费下载，立即算你的 JUPAS 分数。" },
    },
    en: {
        nav: { features: "Features", scores: "Admission scores", faq: "FAQ", blog: "Guides", cta: "Download" },
        resultsBanner: { label: "2027 Admissions Planning", text: "Compare scoring methods, programmes and admission chances early", cta: "Read the guides" },
        hero: {
            tagline: "JUPAS Calculator · Admission Analysis · Interview Sim",
            title: "JUPAS Calculator: Score Your DSE Results in a Second",
            titleHighlight: "Then Compare Admission Chances and Outcomes",
            subtitle: "Enter your DSE results, score them against each of 417 programmes' own formula, and compare with past median and LQ.",
            bullets: [
                "Formulas for 417 programmes at the eight universities and self-financing institutions",
                "Past admission positions, competition and outcome ratings",
                "AI university interview practice with 1,232 prompts",
            ],
            cta: "Download Free",
            imageAlt: "DSE Jupas app screens",
        },
        features: {
            title: "One app, from scoring to interviews",
            items: [
                { icon: Calculator, title: "Programme-specific scoring", desc: "Best 5, subject weighting and bonus rules handled per programme — no prospectus digging." },
                { icon: Brain, title: "Your position in past intakes", desc: "Your score against each programme's historical median and LQ, with year and formula limits shown." },
                { icon: Award, title: "More than admission scores", desc: "Six outcome ratings — employment, salary, AI resilience and more — compared side by side." },
                { icon: Mic, title: "Practise with an AI interviewer", desc: "1,232 prompts across 14 faculty groups, with bilingual instant feedback." },
            ],
        },
        faq: {
            title: "Common Questions",
            items: [
                { q: "How accurate is the scoring? Where's the data from?", a: "The calculator implements the published admission scoring formulas of the eight universities and self-financing institutions (Best 5, 4C+2X, subject weighting, bonus points, etc.), cross-checked against community-compiled programme scoring methods. Results are for reference only; official admissions follow each institution's announcements." },
                { q: "How many programmes are covered?", a: "The current bundle contains 417 unique JUPAS programme scoring and Outcome Rating profiles, updated against published institutional information." },
                { q: "How does the AI admission analysis work?", a: "It compares your programme-specific score with historical median and LQ data, explains the distance from past admitted cohorts, and adds entrance-requirement, band, interview and outcome context. It is not an admission probability or guarantee." },
                { q: "What is the Outcome Rating?", a: "Outcome Rating is a career-ROI reference for 417 programmes across six dimensions: employment outlook, further-study path, AI resilience, university ranking, salary ROI and skill compounding. It is not official advice and does not measure academic value or personal fit." },
            ],
        },
        cta: { title: "From Results Day to Your University Offer", subtitle: "Download free and score your JUPAS choices now." },
    },
};

const getTranslation = (lang) => translations[lang] || translations["en"];

const FadeUp = ({ children, delay = 0, className, reveal = true }) => (
    <motion.div
        initial={reveal ? { opacity: 0, y: 24 } : false}
        whileInView={reveal ? { opacity: 1, y: 0 } : undefined}
        viewport={{ once: true, margin: "-40px" }}
        transition={{ duration: 0.55, delay, ease: [0.22, 1, 0.36, 1] }}
        className={className}
    >
        {children}
    </motion.div>
);

const FAQItem = ({ question, answer, isOpen, onClick }) => (
    <div className="border-b border-gray-100 last:border-b-0">
        <button onClick={onClick} className="w-full flex items-center justify-between py-5 text-left group">
            <span className="text-base font-semibold text-gray-800 group-hover:text-amber-500 transition-colors pr-6 leading-snug">{question}</span>
            <div className={cn("w-7 h-7 rounded-full bg-amber-50 flex items-center justify-center flex-shrink-0 transition-transform duration-200", isOpen && "rotate-180 bg-amber-500")}>
                <ChevronDown size={15} className={cn("text-amber-500 transition-colors", isOpen && "text-white")} />
            </div>
        </button>
        <AnimatePresence>
            {isOpen && (
                <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.22 }} className="overflow-hidden">
                    <p className="pb-5 text-gray-500 leading-relaxed text-sm pr-10">{answer}</p>
                </motion.div>
            )}
        </AnimatePresence>
    </div>
);

const BLOG_POSTS = [
    {
        url: "/blog/dse-results-day-2026-guide/",
        en: { category: "Results day", title: "DSE results day 2026: timeline, the 48-hour JUPAS change window and allocation", desc: "What to prepare before results day, a results-day checklist, the 48-hour change of choices and the August allocation." },
        image: "/blog-covers/dse-results-day-2026-guide.webp",
        category: "放榜攻略",
        title: "DSE 放榜 2026 攻略｜7 月 15 日放榜日時間表、JUPAS 改選 48 小時、派位全流程",
        desc: "由放榜前準備、放榜日行動清單，到 48 小時改選同 8 月派位補選，拆清 2026 放榜季每個關鍵日期。",
        readTime: "11 分鐘",
    },
    {
        url: "/blog/jupas-scoring-methods-explained/",
        en: { category: "Scoring", title: "Why the same DSE results score differently at each university: Best 5, 4C+2X explained", desc: "How far apart the universities' scoring can be — Best 5, 4C+2X, subject weighting and bonus scales." },
        image: "/blog-covers/jupas-scoring-methods-explained.webp",
        category: "計分攻略",
            title: "同一張 DSE 成績單點解間間大學計分唔同？JUPAS Best 5、4C+2X 全拆解",
            desc: "八大院校點計分可以差幾遠？Best 5、4C+2X、科目加權、加分制一次過拆清。",
        readTime: "12 分鐘",
    },
    {
        url: "/blog/jupas-band-a-strategy/",
        en: { category: "Choices", title: "How to order your 20 JUPAS choices: a Band A strategy", desc: "Institutions see only your Band, but allocation follows your real order; check preferences, requirements and past data." },
        image: "/blog-covers/jupas-band-a-strategy.webp",
        category: "選科策略",
            title: "20 個 JUPAS 志願點排先唔會放榜得個吉？Band A 排位策略全拆解",
            desc: "院校只會看到志願 Band，但聯招派位仍按你的實際次序處理；用真實喜好、入學要求及歷年數據逐項核對。",
        readTime: "11 分鐘",
    },
    {
        url: "/blog/jupas-admission-scores-2026/",
        en: { category: "Admission data", title: "JUPAS admission scores 2026: what median and LQ mean, with published figures", desc: "Median, lower quartile and admission thresholds are different things; how to compare across years and formulas." },
        image: "/blog-covers/jupas-admission-scores-2026.webp",
        category: "收生數據",
            title: "JUPAS 收生分數 2026｜Median、LQ 意思點睇？附已公布院校數字",
            desc: "分清中位數、下四分位與錄取門檻，了解年份及計分公式不同時應如何比較。",
        readTime: "13 分鐘",
    },
    {
        url: "/blog/university-interview-preparation/",
        en: { category: "Interviews", title: "University interview questions for medicine, law and business, with the STAR framework", desc: "Common interview question types with a STAR answer framework and mock interview tips." },
        image: "/blog-covers/university-interview-preparation.webp",
        category: "面試攻略",
            title: "大學面試一開口就扣分？醫科、法律、商科常見題 + STAR 答題框架",
            desc: "面試一緊張就口窒窒？拆解神科最常考題型，附 STAR 答題框架同 mock interview 方法。",
        readTime: "12 分鐘",
    },
    {
        url: "/blog/jupas-change-of-choices-guide/",
        en: { category: "JUPAS timeline", title: "Scored lower than expected? JUPAS change-of-choice timeline and recovery strategy", desc: "Every JUPAS change window from December to results day, and how to adjust your choices." },
        image: "/blog-covers/jupas-change-of-choices-guide.webp",
        category: "JUPAS 流程",
            title: "DSE 分數比預期差怕入唔到 U？JUPAS 改選時間線同放榜前後逆襲策略",
            desc: "分數失手仲有冇得救？由 12 月到放榜，拆清每個 JUPAS 改選窗口同補位策略。",
        readTime: "10 分鐘",
    },
];

export default function LandingPage({ initialLang = "zh-HK" }) {
    const [lang, setLang] = useState(initialLang);
    const [langMenuOpen, setLangMenuOpen] = useState(false);
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const [openFAQ, setOpenFAQ] = useState(0);
    const [showMobileCTA, setShowMobileCTA] = useState(false);

    React.useEffect(() => { setLang(initialLang); }, [initialLang]);

    useEffect(() => {
        const update = () => {
            const y = window.scrollY;
            const docH = document.documentElement.scrollHeight;
            const winH = window.innerHeight;
            const nearBottom = y + winH > docH - 200;
            setShowMobileCTA(y > 400 && !nearBottom);
        };
        window.addEventListener("scroll", update, { passive: true });
        update();
        return () => window.removeEventListener("scroll", update);
    }, []);

    const t = getTranslation(lang);
    const currentLang = LANGUAGES.find((l) => l.code === lang) || LANGUAGES[0];
    const showChineseName = lang.startsWith("zh");

    return (
        <div className="min-h-screen font-sans bg-white overflow-hidden">
            {/* ===== NAVBAR ===== */}
            <nav className="fixed top-0 w-full z-50 bg-white/90 backdrop-blur-md border-b border-gray-100">
                <div className="container mx-auto px-6 h-16 flex items-center justify-between max-w-6xl">
                    <a href="/" className="flex items-center gap-2.5">
                        <img src="/logo-transparent-96.webp" alt={tr(lang,"DSE Jupas 神器")} className="w-10 h-10 object-contain" width="96" height="96" />
                        <div className="leading-tight">
                            <span className="font-bold text-gray-900 text-sm block">{tr(lang,"DSE Jupas 神器")}</span>
                            <span className="text-[10px] text-gray-600 block">{tr(lang,"JUPAS 計分 ・ 出路評級 ・ 入學分析")}</span>
                        </div>
                    </a>

                    {/* Desktop Nav */}
                    <div className="hidden md:flex items-center gap-8">
                        <div className="flex gap-7 text-sm text-gray-500">
                            <a href="#features" className="hover:text-amber-500 transition-colors font-medium">{t.nav.features}</a>
                            <a href="/universities/" className="hover:text-amber-500 transition-colors font-medium">{t.nav.scores}</a>
                            <a href="/blog/" className="hover:text-amber-500 transition-colors font-medium">{t.nav.blog}</a>
                            <a href="#faq"      className="hover:text-amber-500 transition-colors font-medium">{t.nav.faq}</a>
                        </div>
                        {/* Language picker */}
                        <div className="relative">
                            <button onClick={() => setLangMenuOpen(!langMenuOpen)} className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-800 transition-colors">
                                <Globe size={14} /><span>{currentLang.name}</span>
                                <ChevronDown size={12} className={cn("transition-transform", langMenuOpen && "rotate-180")} />
                            </button>
                            {langMenuOpen && (
                                <div className="absolute right-0 mt-2 w-52 bg-white rounded-2xl shadow-xl border border-gray-100 py-2 z-50 max-h-72 overflow-y-auto">
                                    {LANGUAGES.map((l) => (
                                        <a key={l.code} href={l.code === "zh-HK" ? "/" : `/${l.code.toLowerCase()}/`}
                                            className={cn("block px-4 py-2 text-sm text-gray-600 hover:bg-amber-50 hover:text-amber-500 transition-colors", lang === l.code && "text-amber-500 font-semibold bg-amber-50")}>
                                            {l.name}
                                        </a>
                                    ))}
                                </div>
                            )}
                        </div>
                        <a href="https://apps.apple.com/app/id6780134101"
                            className="bg-amber-500 hover:bg-amber-600 text-white text-sm font-semibold px-5 py-2 rounded-full transition-colors shadow-md shadow-amber-200">
                            {t.nav.cta}
                        </a>
                    </div>

                    {/* Mobile burger */}
                    <button onClick={() => setMobileMenuOpen(true)} className="md:hidden p-2 rounded-lg hover:bg-gray-100 transition-colors" aria-label={tr(lang,"開啟選單")}>
                        <Menu size={22} className="text-gray-700" />
                    </button>
                </div>
            </nav>

            {/* ===== MOBILE MENU ===== */}
            <AnimatePresence>
                {mobileMenuOpen && (
                    <>
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 bg-black/30 z-50 md:hidden" onClick={() => setMobileMenuOpen(false)} />
                        <motion.div initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", damping: 28, stiffness: 300 }} className="fixed top-0 right-0 h-full w-72 bg-white z-50 shadow-2xl">
                            <div className="p-6">
                                <div className="flex items-center justify-between mb-8">
                                    <div className="flex items-center gap-2">
                                        <img src="/logo-transparent-96.webp" alt={tr(lang,"DSE Jupas 神器")} className="w-9 h-9 object-contain" width="96" height="96" />
                                        <div className="leading-tight">
                                            <span className="font-bold text-gray-900 text-sm block">{tr(lang,"DSE Jupas 神器")}</span>
                                            <span className="text-[10px] text-gray-600 block">{tr(lang,"JUPAS 計分 ・ 出路評級 ・ 入學分析")}</span>
                                        </div>
                                    </div>
                                    <button onClick={() => setMobileMenuOpen(false)} className="p-1.5 rounded-lg hover:bg-gray-100" aria-label={tr(lang,"關閉選單")}>
                                        <X size={20} className="text-gray-600" />
                                    </button>
                                </div>
                                <nav className="flex flex-col gap-1">
                                    {[
                                        { label: t.nav.features, href: "#features" },
                                        { label: t.nav.scores,   href: "/universities/" },
                                        { label: t.nav.blog,     href: "/blog/" },
                                        { label: t.nav.faq,      href: "#faq"      },
                                    ].map((item) => (
                                        <a key={item.href} href={item.href} onClick={() => setMobileMenuOpen(false)}
                                            className="flex items-center justify-between text-gray-700 py-3 px-3 rounded-xl hover:bg-amber-50 hover:text-amber-500 transition-colors font-medium">
                                            {item.label} <ChevronRight size={16} className="text-gray-300" />
                                        </a>
                                    ))}
                                </nav>
                                <div className="mt-6 pt-6 border-t border-gray-100">
                                    <a href="https://apps.apple.com/app/id6780134101"
                                        className="block text-center bg-amber-500 text-white font-semibold py-3 rounded-xl hover:bg-amber-600 transition-colors">
                                        {t.nav.cta}
                                    </a>
                                </div>
                            </div>
                        </motion.div>
                    </>
                )}
            </AnimatePresence>

            {/* ===== SEASONAL RESULTS-DAY BANNER ===== */}
            {t.resultsBanner && (
                <div className="pt-16">
                    <a
                        href="/blog/"
                        className="block bg-amber-700 hover:bg-amber-800 transition-colors text-white"
                    >
                        <div className="container mx-auto px-6 max-w-6xl py-2.5 flex items-center justify-center gap-2 text-center text-sm font-medium flex-wrap">
                            <span className="inline-flex items-center gap-1.5 bg-white rounded-full px-2.5 py-0.5 text-xs font-bold tracking-wide text-amber-900">
                                <span className="w-1.5 h-1.5 rounded-full bg-white animate-pulse" />
                                {t.resultsBanner.label}
                            </span>
                            <span>{t.resultsBanner.text}</span>
                            <span className="underline underline-offset-2 font-semibold">{t.resultsBanner.cta} →</span>
                        </div>
                    </a>
                </div>
            )}

            {/* ===== HERO ===== */}
            <section className={`hero-gradient pb-20 md:pb-28 relative overflow-hidden ${t.resultsBanner ? 'pt-12 md:pt-16' : 'pt-24 md:pt-32'}`}>
                <div className="container mx-auto px-6 max-w-6xl relative">
                    <div className="grid md:grid-cols-2 gap-12 items-center">
                        {/* Left: Text */}
                        <div className="relative">
                            <FadeUp reveal={false}>
                                <div className="inline-flex items-center gap-2 bg-amber-100 text-amber-800 text-xs font-bold px-4 py-1.5 rounded-full mb-6 tracking-wide uppercase">
                                    <div className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse" />
                                    {t.hero.tagline}
                                </div>
                            </FadeUp>
                            <FadeUp delay={0.08} reveal={false}>
                                <h1 className="text-3xl md:text-4xl lg:text-5xl font-extrabold text-gray-900 leading-[1.15] tracking-tight mb-4">
                                    {t.hero.title}<br />
                                    <span className="gradient-text">{t.hero.titleHighlight}</span>
                                </h1>
                            </FadeUp>
                            <FadeUp delay={0.16} reveal={false}>
                                <p className="text-base text-gray-500 leading-relaxed mb-5 max-w-lg">
                                    {t.hero.subtitle}
                                </p>
                            </FadeUp>
                            {t.hero.bullets && (
                                <FadeUp delay={0.20} reveal={false}>
                                    <ul className="space-y-2.5 mb-8 max-w-lg">
                                        {t.hero.bullets.map((b, i) => (
                                            <li key={i} className="flex items-start gap-2.5 text-sm text-gray-600">
                                                <CheckCircle2 className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
                                                <span>{b}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </FadeUp>
                            )}
                            <FadeUp delay={0.26} className="flex flex-wrap gap-3" reveal={false}>
                                <a href="https://apps.apple.com/app/id6780134101" className="hover:opacity-90 transition-opacity">
                                    <img src="/ios-icon.png" alt="Download on App Store" className="h-12 w-auto" width="288" height="86" />
                                </a>
                                <a href="https://play.google.com/store/apps/details?id=app.jupas.dse" className="hover:opacity-90 transition-opacity">
                                    <img src="/android-icon.png" alt="Get it on Google Play" className="h-12 w-auto" width="289" height="86" />
                                </a>
                            </FadeUp>
                        </div>

                        {/* Right: real app screens in phone frames */}
                        <FadeUp delay={0.12} className="flex justify-center md:justify-end" reveal={false}>
                            <div className="relative">
                                {/* Soft glow */}
                                <div className="absolute inset-0 bg-amber-300/25 blur-3xl rounded-full scale-90" />
                                <img
                                    src="/app/hero_phones.webp"
                                    className="relative w-[300px] sm:w-[360px] md:w-[420px] h-auto block"
                                    alt={t.hero.imageAlt}
                                    width="840"
                                    height="1160"
                                    loading="eager"
                                    decoding="async"
                                    fetchpriority="high"
                                />
                            </div>
                        </FadeUp>
                    </div>
                </div>
            </section>

            {lang === "zh-HK" && <JupasChineseQuickCalculator />}
            {lang === "en" && <JupasEnglishQuickCalculator />}

            {/* ===== ADMISSION SCORES BY INSTITUTION ===== */}
            <section id="scores" className="py-14 bg-amber-50/60" aria-label={tr(lang,"院校收生分數")}>
                <div className="container mx-auto px-6 max-w-6xl">
                    <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900 mb-2">{tr(lang,"按院校睇 2023–2026 JUPAS 收生分數")}</h2>
                    <p className="text-gray-600 mb-6">{tr(lang,"科大、理大、港大、都大已公布 2026 年收生分數；全部 417 個課程各有獨立頁面，附 Median、LQ、計分方法及公式變更備註。")}</p>
                    <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
                        {[
                            ["hku", "HKU", "港大", true], ["cuhk", "CUHK", "中大", false], ["hkust", "HKUST", "科大", true],
                            ["polyu", "PolyU", "理大", true], ["cityu", "CityU", "城大", false], ["hkbu", "HKBU", "浸大", false],
                            ["lingu", "LingU", "嶺大", false], ["eduhk", "EdUHK", "教大", false], ["hkmu", "HKMU", "都大", true],
                            ["sssdp", "SSSDP", "自資院校", false],
                        ].map(([slug, code, zh, has2026]) => (
                            <a key={slug} href={`/universities/${slug}/`} className="block bg-white border border-amber-200 rounded-xl px-4 py-3 text-gray-900 hover:border-amber-500">
                                <strong className="block">{code}{lang === "en" ? "" : ` ${tr(lang, zh)}`}</strong>
                                <span className="text-xs text-gray-500">{has2026 ? tr(lang,"已更新 2026") : tr(lang,"2025 數字")}</span>
                            </a>
                        ))}
                    </div>
                    <a href="/universities/" className="inline-block mt-5 text-sm font-semibold text-amber-800">{tr(lang,"查看院校收分目錄 →")}</a>
                    {lang === "en" && <p className="text-xs text-gray-500 mt-2">Score pages are in Traditional Chinese.</p>}
                </div>
            </section>

            {/* ===== FEATURES ===== */}
            <section id="features" className="py-16 bg-white">
                <div className="container mx-auto px-6 max-w-6xl">
                    <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900 mb-8 text-center">{t.features.title}</h2>
                    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                        {t.features.items.map((feature) => (
                            <div key={feature.title} className="rounded-2xl border border-gray-100 bg-slate-50 p-5">
                                <feature.icon size={22} className="text-amber-500 mb-3" />
                                <h3 className="font-bold text-gray-900 mb-1.5">{feature.title}</h3>
                                <p className="text-sm text-gray-500 leading-relaxed">{feature.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ===== BLOG ===== */}
            <section id="blog" className="py-16 bg-gray-50">
                <div className="container mx-auto px-6 max-w-6xl">
                    <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900 mb-8 text-center">{tr(lang,"JUPAS 升學攻略")}</h2>
                    <div className="grid md:grid-cols-3 gap-3">
                        {BLOG_POSTS.slice(0, 6).map((post) => (
                            <a key={post.url} href={post.url} className="group flex flex-col bg-white rounded-xl border border-gray-100 hover:border-amber-300 p-4">
                                <span className="text-xs font-bold text-amber-800 mb-1.5">{lang === "en" ? post.en.category : post.category}</span>
                                <span className="font-semibold text-gray-900 text-sm leading-snug line-clamp-2 group-hover:text-amber-600">{lang === "en" ? post.en.title : post.title}</span>
                            </a>
                        ))}
                    </div>
                    <div className="text-center mt-6">
                        <a href="/blog/" className="inline-flex items-center gap-1.5 text-gray-500 hover:text-amber-600 text-sm font-medium">
                            {tr(lang,"查看所有升學攻略")} <ChevronRight size={14} />
                        </a>
                    </div>
                </div>
            </section>

            {/* ===== FAQ ===== */}
            <section id="faq" className="py-16 bg-white">
                <div className="container mx-auto px-6 max-w-2xl">
                    <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900 mb-8 text-center">{t.faq.title}</h2>
                    <div className="bg-white rounded-3xl border border-gray-100 shadow-sm px-6">
                        {t.faq.items.map((item, i) => (
                            <FAQItem key={i} question={item.q} answer={item.a} isOpen={openFAQ === i} onClick={() => setOpenFAQ(openFAQ === i ? -1 : i)} />
                        ))}
                    </div>
                </div>
            </section>

            {/* ===== CTA ===== */}
            <section className="pb-16">
                <div className="container mx-auto px-6 max-w-4xl">
                    <div className="cta-gradient rounded-3xl px-8 py-12 text-center">
                        <h2 className="text-2xl md:text-3xl font-extrabold text-white mb-2">{t.cta.title}</h2>
                        <p className="text-amber-50 mb-8">{t.cta.subtitle}</p>
                        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                            <a href="https://apps.apple.com/app/id6780134101" className="hover:opacity-90 transition-opacity">
                                <img src="/ios-icon.png" alt="Download on App Store" className="h-12 w-auto" width="288" height="86" loading="lazy" />
                            </a>
                            <a href="https://play.google.com/store/apps/details?id=app.jupas.dse" className="hover:opacity-90 transition-opacity">
                                <img src="/android-icon.png" alt="Get it on Google Play" className="h-12 w-auto" width="289" height="86" loading="lazy" />
                            </a>
                        </div>
                    </div>
                </div>
            </section>

            {/* Sticky mobile download bar */}
            <div className={cn(
                "md:hidden fixed bottom-0 left-0 right-0 z-50 transition-transform duration-300 ease-[cubic-bezier(0.16,1,0.3,1)]",
                showMobileCTA ? "translate-y-0" : "translate-y-full"
            )}>
                <div className="bg-white/95 backdrop-blur-xl border-t border-gray-200 shadow-[0_-4px_20px_rgba(0,0,0,0.08)] px-3 pt-3 pb-[max(12px,env(safe-area-inset-bottom))]">
                    <div className="flex items-center gap-2.5">
                        <img src="/logo-80.webp" alt={tr(lang,"DSE Jupas 神器")} className="w-10 h-10 rounded-xl border border-amber-100 flex-shrink-0" width={40} height={40} />
                        <div className="min-w-0 flex-1">
                            <p className="text-[13px] font-bold text-gray-900 leading-tight truncate">
                                {showChineseName ? tr(lang,"DSE Jupas 神器") : "DSE Jupas"}
                            </p>
                            <p className="text-[10.5px] text-gray-400 leading-tight mt-0.5 flex items-center gap-1">
                                <span>{tr(lang,"JUPAS 計分")}</span>
                                <span className="text-gray-300">·</span>
                                <span>{t.hero.cta}</span>
                            </p>
                        </div>
                        <a href="https://apps.apple.com/app/id6780134101" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 bg-amber-500 active:bg-amber-600 text-white text-[12px] font-semibold px-3 py-2 rounded-lg shadow-sm flex-shrink-0">
                            <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z"/></svg>
                            iOS
                        </a>
                        <a href="https://play.google.com/store/apps/details?id=app.jupas.dse" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 bg-white text-gray-900 border border-gray-200 active:border-amber-300 text-[12px] font-semibold px-3 py-2 rounded-lg shadow-sm flex-shrink-0">
                            <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M3 20.61V3.39a1 1 0 0 1 1.53-.85l14.12 8.61a1 1 0 0 1 0 1.7L4.53 21.46A1 1 0 0 1 3 20.61z"/></svg>
                            Android
                        </a>
                    </div>
                </div>
            </div>

        </div>
    );
}
